name: Nix

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  flake-check:
    name: flake check
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Code checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa # v23

      - name: nix flake check
        run: nix flake check
